### ISSUE TITLE
Fails to anonymize LEI file with Mitra global patient ID when using pydicom 2.2.x

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/dicognito#118]
module | version
------ | -------
platform | Windows-10-10.0.18363-SP0
Python | 3.10.0 (tags/v3.10.0:b494f59, Oct 4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
dicognito | 0.12.0
pydicom | 2.2.2

Error is like 
```
Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 525, in _convert_value
    val.append
AttributeError: 'str' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\valuerep.py", line 752, in __new__
    newval = super().__new__(cls, val)
ValueError: invalid literal for int() with base 10: 'K5JR4D4YWZN7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\tag.py", line 28, in tag_in_exception
    yield
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataset.py", line 2382, in walk
    callback(self, data_element)  # self = this Dataset
  File "D:\Sandbox\dicognito\src\dicognito\anonymizer.py", line 127, in _anonymize_element
    if handler(dataset, data_element):
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 63, in __call__
    if self._anonymize_mitra_global_patient_id(dataset, data_element):
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 78, in _anonymize_mitra_global_patient_id
    self._replace_id(data_element)
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 87, in _replace_id
    data_element.value = self._new_id(data_element.value)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 463, in value
    self._value = self._convert_value(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 527, in _convert_value
    return self._convert(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 541, in _convert
    return pydicom.valuerep.IS(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\valuerep.py", line 755, in __new__
    newval = super().__new__(cls, float(val))
ValueError: could not convert string to float: 'K5JR4D4YWZN7'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\blairyat\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\blairyat\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Sandbox\dicognito\src\dicognito\__main__.py", line 206, in <module>
    main()
  File "D:\Sandbox\dicognito\src\dicognito\__main__.py", line 182, in main
    anonymizer.anonymize(dataset)
  File "D:\Sandbox\dicognito\src\dicognito\anonymizer.py", line 121, in anonymize
    dataset.walk(self._anonymize_element)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataset.py", line 2380, in walk
    with tag_in_exception(tag):
  File "C:\Users\blairyat\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\tag.py", line 32, in tag_in_exception
    raise type(exc)(msg) from exc
ValueError: With tag (0031, 1020) got exception: could not convert string to float: 'K5JR4D4YWZN7'
Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 525, in _convert_value
    val.append
AttributeError: 'str' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\valuerep.py", line 752, in __new__
    newval = super().__new__(cls, val)
ValueError: invalid literal for int() with base 10: 'K5JR4D4YWZN7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\tag.py", line 28, in tag_in_exception
    yield
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataset.py", line 2382, in walk
    callback(self, data_element)  # self = this Dataset
  File "D:\Sandbox\dicognito\src\dicognito\anonymizer.py", line 127, in _anonymize_element
    if handler(dataset, data_element):
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 63, in __call__
    if self._anonymize_mitra_global_patient_id(dataset, data_element):
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 78, in _anonymize_mitra_global_patient_id
    self._replace_id(data_element)
  File "D:\Sandbox\dicognito\src\dicognito\idanonymizer.py", line 87, in _replace_id
    data_element.value = self._new_id(data_element.value)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 463, in value
    self._value = self._convert_value(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 527, in _convert_value
    return self._convert(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\dataelem.py", line 541, in _convert
    return pydicom.valuerep.IS(val)
  File "D:\Sandbox\dicognito\.venv\lib\site-packages\pydicom\valuerep.py", line 755, in __new__
    newval = super().__new__(cls, float(val))
ValueError: could not convert string to float: 'K5JR4D4YWZN7'
```

**Comment by blairconrad** [comment]
Appears to be caused by pydicom/pydicom#1051, first added to v2.2.0.
With this change, certain "well-known" private tags have their VRs applied when being read from a datasource with implicit VRs.
Previously, these tags would've been considered to be UNs.

No the mitra global patient ID is considered to be an IS. This is because pydicom imports its dictionary of well-known private tags from malaterre/GDCM, and that [dictionary lists](https://github.com/malaterre/GDCM/blob/008e437d6ea81979bfa23301ae6e62f82272fe64/Source/DataDictionary/privatedicts.xml#L4466) "MITRA LINKED ATTRIBUTES 1.0" (0031,xx20) as an IS.
