### ISSUE TITLE
Unable to anonymize dataset with encapsulated pixel data that contains embedded sequence delimiter

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/dicognito#96]
**Describe the bug**
When anonymizing a DICOM file that includes encapsulated pixel data as described in [A.4 Transfer Syntaxes For Encapsulation of Encoded Pixel Data](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_A.4.html), that is 
1. (7FE0,0010) has VR OB with length 0xFFFFFFFF and
2. there's at least one data stream fragment beginning with a tag (FFFE,E000) _with an explicit length_

if the data fragment contains 4 consecutive bytes FE FF DD E0, which would be how the terminating Sequence Delimiter Item tag would appear, the `fileutil.read_undefined_length_value` method considers the fragment to end at the delimiter

After the read, the pixel data element's value's length is short, cut off at the point the Sequence Delimiter Item appears, with assumed additional tags following. Then s the anonymization attempts to access the dataset via `walk`, we see the following error:

```
Expected 4 zero bytes after undefined length delimiter at pos 0bf4
Traceback (most recent call last):
  File "D:\Sandbox\pydicom\pydicom\dataelem.py", line 735, in DataElement_from_raw
    value = convert_value(VR, raw, encoding)
  File "D:\Sandbox\pydicom\pydicom\values.py", line 623, in convert_value
    raise NotImplementedError(message)
NotImplementedError: Unknown Value Representation '0x01 0x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\pydicom\pydicom\tag.py", line 27, in tag_in_exception
    yield
  File "D:\Sandbox\pydicom\pydicom\dataset.py", line 2032, in walk
    data_element = self[tag]
  File "D:\Sandbox\pydicom\pydicom\dataset.py", line 861, in __getitem__
    self[tag] = DataElement_from_raw(data_elem, character_set)
  File "D:\Sandbox\pydicom\pydicom\dataelem.py", line 737, in DataElement_from_raw
    raise NotImplementedError("{0:s} in tag {1!r}".format(str(e), raw.tag))
NotImplementedError: Unknown Value Representation '0x01 0x00' in tag (0000, 0000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Sandbox\dicognito\src\dicognito\__main__.py", line 142, in <module>
    main()
  File "D:\Sandbox\dicognito\src\dicognito\__main__.py", line 119, in main
    anonymizer.anonymize(dataset)
  File "D:\Sandbox\dicognito\src\dicognito\anonymizer.py", line 119, in anonymize
    dataset.walk(self._anonymize_element)
  File "D:\Sandbox\pydicom\pydicom\dataset.py", line 2039, in walk
    dataset.walk(callback)
  File "c:\program files (x86)\python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Sandbox\pydicom\pydicom\tag.py", line 34, in tag_in_exception
    raise type(ex)(msg)
NotImplementedError: With tag (0000, 0000) got exception: Unknown Value Representation '0x01 0x00' in tag (0000, 0000)
Traceback (most recent call last):
  File "D:\Sandbox\pydicom\pydicom\dataelem.py", line 735, in DataElement_from_raw
    value = convert_value(VR, raw, encoding)
  File "D:\Sandbox\pydicom\pydicom\values.py", line 623, in convert_value
    raise NotImplementedError(message)
NotImplementedError: Unknown Value Representation '0x01 0x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sandbox\pydicom\pydicom\tag.py", line 27, in tag_in_exception
    yield
  File "D:\Sandbox\pydicom\pydicom\dataset.py", line 2032, in walk
    data_element = self[tag]
  File "D:\Sandbox\pydicom\pydicom\dataset.py", line 861, in __getitem__
    self[tag] = DataElement_from_raw(data_elem, character_set)
  File "D:\Sandbox\pydicom\pydicom\dataelem.py", line 737, in DataElement_from_raw
    raise NotImplementedError("{0:s} in tag {1!r}".format(str(e), raw.tag))
NotImplementedError: Unknown Value Representation '0x01 0x00' in tag (0000, 0000)```
```

**Expected behavior**
The dataset would be anonymized.

**Steps To Reproduce**
Discovered when opening a patient's Video Endoscopic Image (1.2.840.10008.5.1.4.1.1.77.1.1.1), which I can't share because of PHI concerns, and also it's quite large. See [JPEG2000-embedded-sequence-delimiter.zip](https://github.com/pydicom/pydicom/files/4876404/JPEG2000-embedded-sequence-delimiter.zip) for a constructed dataset. After extracting, attempt to anonymize it.

**Environment**

module       | version
------       | -------
platform     | Windows-10-10.0.18362-SP0
Python       | 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
pydicom      | 2.1.0.dev0 (b9fb05c177b685bf683f7f57b2d57374eb7d882d)
dicognito     | any version, including current master (7e9b0682a40fa746980b99fb9baf399e17eb0b15)

**Cause**

This is caused by https://github.com/pydicom/pydicom/issues/1140.

**Comment by blairconrad** [comment]
The underlying bug has been fixed in the master branch of pydicom, so the ultimate fix in dicognito will be to require a minimum of pydicom 2.1.0 (the expected version number that will contain the fix), but that's not slated for release until November, as I type.

Until pydicom 2.1.0 is released, you can workaround by [installing a development version from their github repo](https://pydicom.github.io/pydicom/stable/tutorials/installation.html#install-the-development-version).
